app:
  name: 'auth-service'
  version: '1.0.0'

http:
  port: '8080'
  read_timeout: 15
  write_timeout: 15
  shutdown_timeout: 15

auth:
  signing_key: "secret"
  hash_salt: "sugar"
  token_ttl: 20000

logger:
  log_level: 'debug'
  rollbar_env: 'go-clean-template'

postgres:
  pool_max: 5
